name: helloworld

on:
    push:
     branches: ['enh/10/complete-refactor']
    #  paths:
    #     - ".github/workflows/hello.yml"

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Hello step
        run: echo "hello world"